### ISSUE TITLE
Not an issue but would be good to add a name of the database 

### ISSUE THREAD

**Issue by Sumit0071** [Arshpreet-Singh0/JOB-PORTAL#1]
change the config file db.js
import mongoose from 'mongoose';

const connectDB = async (DATABASE_URL) => {
  try {
    const DB_OPTIONS = {
      dbName: "JOBDb"
    }
    await mongoose.connect(DATABASE_URL, DB_OPTIONS)
    console.log('Connected Successfully...')
  } catch (error) {
    console.log(error)
  }
}

export default connectDB

**Comment by Arshpreet-Singh0** [comment]
Issue Resolved

Thank you for pointing this out! I have updated the db.js file to explicitly include the database name as JOBDb. The issue has been fixed in commit [a9b3cb0](https://github.com/Arshpreet-Singh0/JOB-PORTAL/commit/a9b3cb0c7a301e002202d352e75a35ddb4520eef).

If you notice anything else, feel free to let me know. I appreciate your feedback! 🚀
